name: Build a Windows executable

on:
  workflow_run:
    workflows: ["Build & Lint & Deploy"]
    types:
      - completed

jobs:
  pyinstaller_win:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install pyinstaller

      - name: Build a Windows executable
        run: |
         python win_build.py

      - uses: actions/upload-artifact@v2
        with:
          name: BasementRenovator
          path: dist/
 


